---

all:
  vars:
  children:
    provision_cluster:  # group - role of provision_cluster
      hosts:
        provision_cluster.default:
    storage_group:
      hosts:
        storage_group.default:
    port_group:
      hosts:
        port_group.default:

