---

all:
  vars:
  children:
    provision_cluster:  # group - role of provision_cluster
      hosts:
        provision_cluster.default:
    create_storage_group:
      hosts:
        create_storage_group.default:
    create_port_group:
      hosts:
        create_port_group.default:
