---
# tasks file for create_maskingview

- name: Verify if storage group, host group and port group are provisioned
  ansible.builtin.include_tasks: verify_provisioning.yml

# - name: Create maskingview when verifications are all true
