---
# tasks file for create_maskingview

- name: Debug from role create_maskingview
  ansible.builtin.debug:
    msg: "Hi, I am creating maskingview!"
  when: debug_mode | default(false)

# - name: Create maskingview when verifications are all true
