---
# tasks file for gather_cluster_info
- name: Gather Cluster Information
  vmware.vmware.cluster_info:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    cluster_name: "{{ vcenter_cluster_name }}"
  register: cluster_info

- name: Print out cluster info
  ansible.builtin.debug:
    msg: "{{ cluster_info }}"
  when: debug_mode | default(false)

- name: Set variable cluster_details (for other roles to use)
  ansible.builtin.set_fact:
    cluster_details: "{{ cluster_info.clusters }}"

- name: Print out cluster details
  ansible.builtin.debug:
    msg: "{{ cluster_details }}"
  when: debug_mode | default(false)
