---
# tasks file for gather_vcenter_cluster_info
# - name: Gather vcenter cluster info
#   vmware.vmware.cluster_info:
#     hostname: "{{ vcenter_hostname }}"
#     username: "{{ vcenter_username }}"
#     password: "{{ vcenter_password }}"
#     validate_certs: "{{ vcenter_validate_certs }}"
#     datacenter_name: "{{ vcenter_datacenter_name }}"
#     cluster_name: "{{ vcenter_cluster_name }}"
#   register: cluster_info

# - name: Print out cluster info
#   ansible.builtin.debug:
#     msg: "{{ cluster_info }}"
#   when: debug_mode | default(false)

# - name: Set variable vcenter_hosts list
#   ansible.builtin.set_fact:
#     vcenter_hosts: "{{ (cluster_info.clusters[vcenter_cluster_name].hosts) | map(attribute='name') | list }}"

# - name: Print out vcenter hosts
#   ansible.builtin.debug:
#     msg: "{{ vcenter_hosts }}"
#   when: debug_mode | default(false)

- name: Gather info about vmhbas of all ESXi Host in the given Cluster
  community.vmware.vmware_host_vmhba_info:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    cluster_name: '{{ vcenter_cluster_name }}'
    validate_certs: "{{ vcenter_validate_certs }}"
  register: cluster_hosts_vmhbas

- name: Print out cluster hosts vmhbas details
  ansible.builtin.debug:
    msg: "{{ cluster_hosts_vmhbas.hosts_vmhbas_info }}"  # type_debug: dict
  when: debug_mode | default(false)

# Extract hosts' port_wwn for those type of Fibre Channel and construct a list of dict, in which the key
# is the host name and the value is a list of port_wwn
- name: Extract fibre channel type host and port_wwn into a list
  ansible.builtin.set_fact:
    fibre_channel_host_list: >-
      {{
        cluster_hosts_vmhbas.hosts_vmhbas_info | dict2items |
        json_query('[*].{host: key, port_wwn: value.vmhba_details[?type==`Fibre Channel`].port_wwn}')
      }}

- name: Display extracted Fibre Channel information
  ansible.builtin.debug:
    msg: "{{ fibre_channel_host_list }}"
  when: debug_mode | default(false)
