---

# Assertion gets called when a new storage group is created
- name: Get newly created storage group
  dellemc.powermax.storagegroup:
    unispherehost: "{{ unisphere_host }}"
    universion: "{{ unisphere_version }}"
    user: "{{ unisphere_user }}"
    password: "{{ unisphere_password }}"
    verifycert: "{{ unisphere_verifycert }}"
    serial_no: "{{ unisphere_serial_no }}"
    sg_name: "{{ vcenter_cluster_name }}_SG"
    state: 'present'
  register: assert_sg

- name: Print out newly created storage group details
  ansible.builtin.debug:
    msg: "{{ assert_sg }}"
  when: debug_mode | default(false)

# - name: Initialize an empty list for composing volume id
#   ansible.builtin.set_fact:
#     composed_volume_ids: []

# - name: Append volume id to a list based on the inventory and naming convention
#   ansible.builtin.set_fact:
#     composed_volume_ids: "{{ composed_volume_ids + [vcenter_cluster_name + '_DATA.' + item | string] }}"
#   loop: "{{ range(0, volume_index, 1) | list }}"

# - name: Print out composed volume id list
#   ansible.builtin.debug:
#     msg: "{{ composed_volume_ids }}"
#   when: debug_mode | default(false)

- name: Assert - storage group name
  ansible.builtin.assert:
    that:
      - "{{ vcenter_cluster_name + '_SG' == assert_sg.storage_group_details.storageGroupId }}"
    fail_msg: "Storage group name does not match! Expected {{ vcenter_cluster_name + '_SG' }} but got {{ assert_sg.storage_group_details.storageGroupId }}"
    success_msg: "This assertion passed!"
