---

all:
  vars:
  children:
    create_hosts_hostgroup:
      hosts:
        create_hosts_hostgroup.default:

    create_storage_group:
      hosts:
        create_storage_group.default:

    create_volumes:
      hosts:
        create_volumes.default:

    create_port_group:
      hosts:
        create_port_group.default:

    create_maskingview:
      hosts:
        create_maskingview.default:

    create_esxi_host_datastore:
      hosts:
        create_esxi_host_datastore.default:
