---

all:
  vars:
  children:    
    create_hosts_hostgroup:
      hosts:
        create_hosts_hostgroup.default:

    create_storage_group:
      hosts:
        create_storage_group.default:
    
    create_port_group:
      hosts:
        create_port_group.default:

    create_maskingview:
      hosts:
        create_maskingview.default:
    