---

all:
  vars:
  children:
    provision_cluster:  # group - role of provision_cluster
      hosts:
        provision_cluster.default:
    
    create_hosts_hostgroup:
      hosts:
        create_hosts_hostgroup.default:

    create_storage_group:
      hosts:
        create_storage_group.default:
    
    create_port_group:
      hosts:
        create_port_group.default:

    create_maskingview:
      hosts:
        create_maskingview.default:
    