---
# serial number
serial_no: '000220002205'

# storage group name
sg_name: 'pmax1_jw-2025'

# vloume base name
vol_name: "ansible_vol"

# host name and initiator - a list of dictionaries
host_name_initiator:
  - host_name: 'Ansible_Cluster_Host3_IG'
    host_initiators:
      - '10000000c99ffaee'
      - '10000000c99ffaef' 
  - host_name: "Ansible_Cluster_Host4_IG"
    host_initiators:
      - '10000000c99ffffe'
      - '10000000c99ffafe'

# host group name
hostgroup_name: 'Ansible_Cluster_2_HG'
  
# port group name
portgroup_name: 'Ansible_Cluster_2_PG'

# port list
port_list:
  - director_id: OR-1C
    port_id: 3
  - director_id: OR-2C
    port_id: 3

# masking view name
mv_name: Ansible_Cluster_2_MV