---
# tasks file for storage_group
- name: Set unisphere common connection
  ansible.builtin.set_fact:
    uni_connection_vars: &uni_connection_vars
      unispherehost: "{{ unispherehost }}"
      universion: "{{ universion }}"
      user: "{{ user }}"
      password: "{{ password }}"
      verifycert: "{{ verifycert }}"
      serial_no: "{{ serial_no }}"

#### Creat Storage Group Operation ####
- name: "Creat Storage Group - create a new storage group and add existing volumnes to it"
  when: state == 'present'
  block:
    - name: Create Empty Storage Group
      collections:
        - dellemc.powermax
      dellemc.powermax.storagegroup:
        <<: *uni_connection_vars
        sg_name: "{{ sg_name }}"
        # service_level: "Bronze" # TODO as Dell lab gives error
        state: 'present'

    - name: Add Volumnes to the Storage Group
      collections:
        - dellemc.powermax
      dellemc.powermax.storagegroup:
        <<: *uni_connection_vars
        sg_name: "{{ sg_name }}"
        # service_level: "Bronze" # TODO as Dell lab gives error
        state: 'present'
        volumes: "{{ volumes }}"
        vol_state: "present-in-group"
      register: create_sg

    - name: Print out storage group
      ansible.builtin.debug:
        msg: "{{ create_sg }}"
      when: debug_mode | default(false)

#### Remove Storage Group Operation ####
- name: "Remove Storage Group - remove existing volumnes from the storage group and then delete the storage group"
  when: state == 'absent'
  block:
    - name: Remove Volumnes from the Storage Group
      collections:
        - dellemc.powermax
      dellemc.powermax.storagegroup:
        <<: *uni_connection_vars
        sg_name: "{{ sg_name }}"
        # service_level: "Bronze" # TODO as Dell lab gives error
        state: 'present'
        volumes: "{{ volumes }}"
        vol_state: "absent-in-group"

    - name: Remove Empty Storage Group
      collections:
        - dellemc.powermax
      dellemc.powermax.storagegroup:
        <<: *uni_connection_vars
        sg_name: "{{ sg_name }}"
        # service_level: "Bronze" # TODO as Dell lab gives error
        state: 'absent'
      register: remove_sg

    - name: Print out storage group after removal
      ansible.builtin.debug:
        msg: "{{ remove_sg }}"
      when: debug_mode | default(false)
