---

# tasks file for create_volumes
- name: Create volumes for newly created storage group
  collections:
    - dellemc.powermax
  dellemc.powermax.volume:
    unispherehost: "{{ unisphere_host }}"
    universion: "{{ unisphere_version }}"
    user: "{{ unisphere_user }}"
    password: "{{ unisphere_password }}"
    verifycert: "{{ unisphere_verifycert }}"
    serial_no: "{{ unisphere_serial_no }}"
    vol_name: "{{ vcenter_cluster_name + '_DATA.' }}{{ item }}"
    sg_name: "{{ vcenter_cluster_name }}_SG"  # Storage group name should be along with volume name
    size: "{{ size }}"
    cap_unit: 'TB'
    state: 'present'
  loop: "{{ range(0, volume_index, 1) | list }}" # 0, 1, 2
  register: volumes_info

- name: Create volume dict (key is volume_identifier and value is WWN) for future reference
  set_fact:
    volume_dict: >-
      {{ volume_dict | default({}) | combine({item.volume_details.volume_identifier: item.volume_details.wwn}) }}
  loop: "{{ volumes_info.results }}"

- name: Print out volume_dict
  ansible.builtin.debug:
    msg: "{{ volume_dict }}"
  when: debug_mode | default(false)
