---
# tasks file for create_hosts_hostgroup

# Unnisphere host connection
- name: Set unisphere common connection
  ansible.builtin.set_fact:
    uni_connection_vars: &uni_connection_vars
      unispherehost: "{{ unisphere_host }}"
      universion: "{{ unisphere_version }}"
      user: "{{ unisphere_user }}"
      password: "{{ unisphere_password }}"
      verifycert: "{{ unisphere_verifycert }}"
      serial_no: "{{ unisphere_serial_no }}"

# Gather vcenter cluster info
- name: Include a task that gathers vcenter cluster info
  ansible.builtin.include_tasks: gather_vcenter_cluster_info.yml

# This list is extracted from vcenter. It is a list of dict where the key is the host name and the value is a list of its
# port_wwn for those type of Fibre Channel and online status
- name: Display extracted Online Fibre Channel host and port_wwn information
  ansible.builtin.debug:
    msg: "{{ online_fibre_channel_host_list }}"
  when: debug_mode | default(false)

- name: Create pmax hosts based on vcenter hosts
  collections:
    - dellemc.powermax
  dellemc.powermax.host:
    <<: *uni_connection_vars
    host_name: "{{ item.host | split('.') | first | upper }}"
    initiators: "{{ item.port_wwn | map('regex_replace', ':', '') | list }}"
    host_flags:
      consistent_lun: true
    state: 'present'
    initiator_state: 'present-in-host'
  loop: "{{ online_fibre_channel_host_list }}"
  register: pmax_hosts

- name: Print out new created pmax_hosts
  ansible.builtin.debug:
    msg: "{{ pmax_hosts.results }}"
  when: debug_mode | default(false)

- name: Create a host group and add hosts to it
  dellemc.powermax.hostgroup:
    <<: *uni_connection_vars
    hostgroup_name: "{{ vcenter_cluster_name }}_HG"
    hosts: "{{ pmax_hosts.results | json_query('[].host_details.hostId') }}"
    host_flags:
      consistent_lun: true
    state: 'present'
    host_state: 'present-in-group'
  register: hg

- name: Set variable hostgroup_name for future reference
  ansible.builtin.set_fact:
    hostgroup_name: "{{ hg.hostgroup_details.hostGroupId }}"

- name: Print out new created hostgroup_name
  ansible.builtin.debug:
    msg: "{{ hostgroup_name }}"
  when: debug_mode | default(false)
