
name: GitHub automations ansible-lint for best practice
on:
  push:
      branches:
        - dev
  pull_request:

jobs:
  AnsibleLint:
    runs-on: self-hosted

    steps:
      - name: check code out from github into 'self-hosted' runner
        uses: actions/checkout@v4.2.1

      - name: Run ansible-lint
        run: |
          ansible-lint
