
name: GitHub automations ansible-lint for best practice
on:
  push:
      branches:
        - dev
  pull_request:

jobs:
  AnsibleLint:
    runs-on: ubuntu-latest     # name of a container (environment) to run your automations in
    steps:
      - name: check code out from github into "ubuntu-latest"
        uses: actions/checkout@v4
      - name: run ansible lint
        uses: ansible/ansible-lint@v6.17.0